### ISSUE TITLE
Test top-hat

### ISSUE THREAD

**Issue by matq007** [nf-core/rnafusion#13]
https://github.com/infphilo/tophat

**Comment by matq007** [comment]
Tried to implement. The only workable version which will timeout I think. Takes like 1 hour and then fails with some error code.
```yaml
name: tophat
channels:
  - bioconda
dependencies:
  - tophat=2.1.0
  - bowtie2=2.2.5
  - blast-legacy=2.2.26
  - blast=2.6.0
```

```bash
mkdir tophatfusion_out

tophat2 \\
-p ${task.cpus} \\
-o . \\
--fusion-search \\
--keep-fasta-order \\
--no-coverage-search \\
--bowtie1 -r 0 --mate-std-dev 80 --max-intron-length 100000 --fusion-min-dist 100000 --fusion-anchor-length 13 --fusion-ignore-chromosomes chrM \\
${bowtie_index}/genome \\
${reads[0]} ${reads[1]} \\

tophat-fusion-post \\
-p ${task.cpus} \\
--num-fusion-reads 1 \\
--num-fusion-pairs 2 \\
--num-fusion-both 5 \\
${bowtie_index}/genome
```

**Comment by matq007** [comment]
Another run was made with this setup
```yml
name: tophat
channels:
  - bioconda
dependencies:
  - tophat=2.1.0
  - bowtie=1.1.2
  - blast-legacy=2.2.26
  - blast=2.6.0
```

There are no results reported but in the output, I can see that it caught some fusions but was not able to resolve them for some reason.

**Comment by matq007** [comment]
## Conda
```yml
name: tophat
channels:
  - bioconda
dependencies:
  - tophat=2.1.0
  - bowtie=1.1.2
  - blast-legacy=2.2.26
  - blast=2.6.0
```
## Code:
```bash
mkdir tophatfusion_out

tophat2 \\
-p ${task.cpus} \\
-o . \\
--fusion-search \\
--keep-fasta-order \\
--no-coverage-search \\
--bowtie1 --fusion-ignore-chromosomes chrM \\
${bowtie_index}/genome \\
${reads[0]} ${reads[1]} \\

tophat-fusion-post \\
-p ${task.cpus} \\
--num-fusion-reads 1 \\
--num-fusion-pairs 2 \\
--num-fusion-both 5 \\
${bowtie_index}/genome
```

## Results:
Tophat alignments works but the tophat-fusion-post is not retrieving any results.

## Notes:
- [Official website](https://ccb.jhu.edu/software/tophat/fusion_tutorial.shtml)
- [External tutorial](http://bioinformatics-ca.github.io/2016_workshops/cancer/gene_fusions/run.html)
- [Blast](http://www.vicbioinformatics.com/documents/Quick_Start_Guide_BLAST_to_BLAST+.pdf)
- **do not update to latest version, fails**
- when using GRCh38 make to delete a header from file `ensGene.txt`, [ref](https://github.com/infphilo/tophat/issues/45).
- make sure to follow the requested directory structure
